// Punto único de acceso a datos. Todos los módulos resuelven a /services/supabase.
export { dashboardService } from "./supabase/dashboard.service";
export * from "./dashboard.types";
export { productosService } from "./supabase/productos.service";
export * from "./productos.types";
export { ventasService } from "./supabase/ventas.service";
export * from "./ventas.types";
export { clientesService } from "./supabase/clientes.service";
export * from "./clientes.types";
export { cajaService } from "./supabase/caja.service";
export * from "./caja.types";
export { comprasService } from "./supabase/compras.service";
export * from "./compras.types";
export { proveedoresService } from "./supabase/proveedores.service";
export * from "./proveedores.types";
export { cotizacionesService } from "./supabase/cotizaciones.service";
export * from "./cotizaciones.types";
export { movimientosService } from "./supabase/movimientos.service";
export * from "./movimientos.types";
export { reportesService } from "./supabase/reportes.service";
export * from "./reportes.types";
export { trabajadoresService } from "./supabase/trabajadores.service";
export * from "./trabajadores.types";
export { auditoriaService } from "./supabase/auditoria.service";
export * from "./auditoria.types";
export { usuariosService } from "./supabase/usuarios.service";
export * from "./usuarios.types";
export { configuracionService } from "./supabase/configuracion.service";
export * from "./configuracion.types";
export { metasService } from "./supabase/metas.service";
export * from "./metas.types";
